apiVersion: v1
kind: Namespace
metadata:
  name: xy3-1
  labels:
    name: xy3-1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity
  namespace: xy3-1
spec:
  selector:
    matchLabels:
      app: activity
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
      labels:
        app: activity
    spec:
      containers:
      - name: activity
        image: docker.io/perterci/activity:v1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9000
          name: grpc
        command:
        - /bin/sh
        - -c
        - |
          export LOG_DIR=/opt/service/log/$K8S_NAMESPACE/$HOSTNAME
          export ZAP_PATH=/opt/service/log/$K8S_NAMESPACE/$HOSTNAME
          exec ./bin/cmd -conf /opt/service/configs/args,/opt/service/configs/base
        env:
        - name: APP_ID
          value: activity
        - name: K8S_NAMESPACE
          value: xy3-1
        - name: SERVERID
          value: 1
        - name: K8S_CROSS_NAMESPACE
          value: xy3-cross
      imagePullSecrets:
      - name: qianzx

---
apiVersion: v1
kind: Service
metadata:
  name: activity
  namespace: xy3-1
spec:
  selector:
    app: activity
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  - protocol: TCP
    port: 9000
    targetPort: 9000
    name: grpc