apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity
  namespace: xy3-{SRV_NO}
spec:
  selector:
    matchLabels:
      app: activity
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
      labels:
        app: activity
    spec:
      containers:
      - name: activity
        image: repo.qianz.com/xy3/activity:{IMAGE_VERSION}
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9000
          name: grpc
        command:
        - /bin/sh
        - -c
        - |
          export LOG_DIR=/opt/service/log/$K8S_NAMESPACE/$HOSTNAME
          export ZAP_PATH=/opt/service/log/$K8S_NAMESPACE/$HOSTNAME
          exec ./bin/cmd -conf /opt/service/configs/args,/opt/service/configs/base
        env:
        - name: APP_ID
          value: activity
        - name: K8S_NAMESPACE
          value: xy3-{SRV_NO}
        - name: SERVERID
          value: "{SRV_NO}"
        - name: K8S_CROSS_NAMESPACE
          value: xy3-cross
        volumeMounts:
        - mountPath: /opt/service/configs
          name: xyconfig
        - mountPath: /opt/service/log
          name: log-path
      imagePullSecrets:
      - name: qianzx
      volumes:
      - name: xyconfig
        persistentVolumeClaim:
          claimName: xy3-cfg-server-all-{SRV_NO}
      - name: log-path
        persistentVolumeClaim:
          claimName: xy3-log-all-{SRV_NO}

---
apiVersion: v1
kind: Service
metadata:
  name: activity
  namespace: xy3-{SRV_NO}
spec:
  selector:
    app: activity
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    name: http
  - protocol: TCP
    port: 9000
    targetPort: 9000
    name: grpc